kind: pipeline
name: build
type: kubernetes

resources:
  requests:
    memory: 512Mi

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    repo: ghcr.io/kubernetize/unbound-telemetry
    registry: ghcr.io
    auto_tag: true
    auto_label: false
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
    - name: docker
      path: /var/lib/docker

volumes:
  - name: docker
    temp: {}
